export const SET_PERIOD_MODE = 'SET_PERIOD_MODE'
export const SET_CELL = 'SET_CELL'
export const SET_GRID_ROWS = 'SET_GRID_COLUMNS'
export const SET_FILTER = 'SET_FILTER'
export const LOAD_TASKS = 'LOAD_TASKS'
